version: 2
updates:
- package-ecosystem: "bundler"
  directory: "/"
  vendor: true
  target-branch: "master"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
